### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [plevold/unicode-in-fortran#1]
I suggest adding the topics `unicode`, `string` in the About section.

**Comment by plevold** [comment]
Thanks for the suggestion, I'm not very good with Github SEO 😅 just added the topics fortran, unicode and strings 👍

**Comment by Beliavsky** [comment]
I'm not a GitHub expert either, but you could add the text "Collection of examples and some explanations on how to use Unicode in Fortran" in the About section.
